version: '3.1'
services:
 media-server:
  env_file: ./.env
  image: ${IMAGE_PATH}:${VERSION}
  network_mode: host
  volumes:
        - "${LOGS_DIR}/:/var/log/wowza/"
  restart: always
  container_name: ms
